version: "2"

services:
  nginx:
    build: nginx
    container_name: "nginx"
    ports:
      - "80:80"
    networks:
      - local
      
  portainer:
    image: portainer/portainer
    container_name: "portainer"
    ports:
      - "9000:9000"
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data  
networks:
  local:
    driver: bridge